import os
from reportlab.pdfgen import canvas

os.makedirs("documents", exist_ok=True)

def write_file(path, lines):
    with open(path, "w", encoding="utf-8") as f:
        for i, line in enumerate(lines, 1):
            f.write(f"{i:03}: {line}\n")

# 1. Short doc
short_line = "This is a short test document line."
write_file("documents/sample_short.txt", [short_line] * 10)

# 2. Long doc with 5+ pages (50 lines per page * 5)
long_lines = []
for i in range(250):  # ~5 pages worth
    long_lines.append(f"This is line {i+1:03} of the long document for paging test.")
write_file("documents/sample_long.txt", long_lines)


# 3. Wrapped doc
wrapped_line = ("This is a long sentence designed to exceed the width of the page and "
                "test how word wrapping works in the CUDA renderer.")
write_file("documents/sample_wrapped.txt", [wrapped_line] * 50)

# 4. Unicode doc
unicode_line = "Emoji & accents: café, résumé, naïve — 👍🔥✨"
write_file("documents/sample_unicode.txt", [unicode_line] * 20)

# 5. .pdoc file (simulated text-based)
write_file("documents/sample.pdoc", [long_lines] * 100)

# 6. PDF file using reportlab
pdf = canvas.Canvas("documents/sample.pdf")
pdf.setFont("Helvetica", 12)
pdf.drawString(100, 800, "Sample PDF Document")
pdf.drawString(100, 780, "This PDF was generated by reportlab.")
for i in range(20):
    pdf.drawString(100, 760 - (i * 20), f"Line {i+1}: Lorem ipsum dolor sit amet...")
pdf.save()

print("✅ Test documents generated in ./documents (TXT, PDC, PDF)")
